[package]
name = "box_benchmark"
version = "0.0.0"
edition = "2018"
publish = false

[[bin]]
name = "box_benchmark"
path = "box_benchmark.rs"

[dependencies]
clap = "2"
fixed-buffer = "^0.1.7"
jemalloc-ctl = "0.3"
jemallocator = "0.3"
structopt = "0.3"
