# https://doc.rust-lang.org/cargo/guide/continuous-integration.html#gitlab-ci
# https://users.rust-lang.org/t/my-gitlab-config-docs-tests/16396/3
# https://docs.gitlab.com/ee/ci/yaml/

stages:
  - stage1

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

before_script:
  - rustc --version && cargo --version

cache:
  # Increment the 'gen' number to clear the caches.
  key: $CI_JOB_NAME-$CI_COMMIT_BRANCH-gen1
  paths:
    - target/
    - cargo/

rust-latest:
  stage: stage1
  image: rust:latest
  script:
    - rustup component add rustfmt clippy
    - ./check.sh

rust-beta:
  stage: stage1
  # Switch to official rust:beta image once it is available: https://github.com/rust-lang/docker-rust/issues/14
  image: instrumentisto/rust:beta
  script:
    - ./check.sh

rust-nightly:
  stage: stage1
  image: rustlang/rust:nightly
  variables:
    CFG_RELEASE_CHANNEL: nightly
    CFG_RELEASE: nightly
  script:
    - rustup component add rustfmt || cargo +nightly install --git https://github.com/rust-lang/rustfmt.git --branch master --force --features "rustfmt cargo-fmt" rustfmt-nightly
    - rustup component add clippy || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
    - ./check.sh
  allow_failure: true
