stages:
  - test_stage

cache:
  when: always
  paths:
    - $CI_PROJECT_DIR/cargo

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

test_job:
  stage: test_stage
  image: rust:latest
  script:
    - cargo check --verbose
    - cargo build --verbose
    - cargo test --verbose
    - rustup component add rustfmt
    - cargo fmt --all -- --check
    - cargo clippy -- -D warnings
