# https://doc.rust-lang.org/cargo/guide/continuous-integration.html#gitlab-ci
# https://users.rust-lang.org/t/my-gitlab-config-docs-tests/16396/3
# https://docs.gitlab.com/ee/ci/yaml/

stages:
  - stage1

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

before_script:
  - rustc --version && cargo --version

cache:
  when: always
  key: $CI_JOB_NAME
  paths:
    - target/
    - $CARGO_HOME

rust-latest:
  stage: stage1
  image: rust:latest
  script:
    - ./check.sh

rust-beta:
  stage: stage1
  # Switch to official rust:beta image once it is available: https://github.com/rust-lang/docker-rust/issues/14
  image: instrumentisto/rust:beta
  script:
    - ./check.sh

rust-nightly:
  stage: stage1
  image: rustlang/rust:nightly
  script:
    - ./check.sh
  allow_failure: true
