[package]
publish = false
name = "fixed-buffer"
description = "Fixed-size buffers for network protocol parsers"
version = "0.1.0"
authors = ["Michael Leonhard <michael@leonhardllc.com>"]
edition = "2018"
repository = "https://github.com/leonhard-llc/fixed-buffer-rs"
readme = "README.md"
license = "Apache-2.0"
keywords = ["io", "network", "tokio", "protocol", "async"]
categories = ["parsing", "network-programming"]

[dependencies]
tokio = { version = "0.3", features = ["io-util"] }

[dev-dependencies]
crc = "1.8"
tokio = { version = "0.3", features = ["macros", "net", "rt-multi-thread", "stream", "time"] }
tokio-util = { version = "0.4.0", features = ["io"] }